BuilderCommon:
  BuilderClass: HnswStreamer
  BuildFile: /root/data/cohere/1m/cohere_train_vector_1m.norm.zvec.vecs
  # NeedTrain: true #是否需要走train流程
  # TrainFile: /root/data/cohere/1m/cohere_train_vector_1m.norm.zvec.vecs
  DumpPath:  ./flase.tmp
  IndexPath: /root/data/cohere/1m/index/cohere.random2.cosine.int8.index

  ThreadCount: 16

  MetricName: Cosine
  ConverterName: CosineInt8Converter
  # ConverterName: Int8StreamingConverter

  DisableIdMap: true

ConverterParams:
    cosine.converter.enable_rotate: !!bool true

BuilderParams: #各Builder方法的params参数
  proxima.hnsw.streamer.efconstruction: !!int 500
  proxima.hnsw.streamer.use_id_map: !!bool false
  proxima.hnsw.streamer.max_neighbor_count: !!int 15
